# Generated by Django 5.0.7 on 2024-08-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auther',
        ),
    ]
